# Generated by Django 5.0.1 on 2024-01-09 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_user_rename_products_product_order_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billed_user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_products',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ordered_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
